In [38]:
import pandas as pd 

path = '27c.xlsx' 

a = pd.read_excel(path)

In [39]:
a

,id,description,vector,category
0,1159419,Лежит женщина,"{0.05818263,0.032113455,-0.02853107,-0.0636563...",1.0
1,1201824,"#НОМЕР#. Дебоширит сын, принимает наркотически...","{0.007246209,0.052625045,-0.004410434,-0.03702...",0.0
2,1052343,"Драка 2 человека, в состоянии алкогольного опь...","{0.06992716,0.036976717,-0.07429831,-0.0511510...",0.0
3,987489,В дом Заявителя ломится знакомый. У Заявителя ...,"{0.05929825,0.10075583,-0.04815824,0.041942403...",0.0
4,1376556,Справка 103 (консультация),"{0.07565966,0.017556518,-0.05588654,0.03299051...",0.0
...,...,...,...,...
9995,641285,"Нет водоснабжения по нескольким улицам, трое с...","{0.0059625385,0.0012267067,0.012396579,-0.0155...",NaN
9996,946051,Сильная боль в области живота.,"{-0.0067766234,-0.0014006067,0.008502565,0.086...",NaN
9997,769676,Знакомый мужчина справляет нужду на месте,"{0.017524539,0.03087422,-0.06456015,-0.0359971...",NaN
9998,1741072,Справка 103 консультация,"{0.07474967,0.022872753,-0.07786103,0.03425507...",NaN
9999,1737742,"Справка 103, о госпитализации родственницы Зая...","{0.016288364,0.015901592,-0.04389199,0.0022961...",NaN

In [40]:
import numpy as np 

a['vector']=a['vector'].apply(lambda x:np.array(x.replace('{','').replace('}','').split(','),dtype=np.float64)) 

print(type(a['vector'][0]),'\n') 

print(a['vector'])

<class 'numpy.ndarray'>

0       [0.05818263, 0.032113455, -0.02853107, -0.0636...
1       [0.007246209, 0.052625045, -0.004410434, -0.03...
2       [0.06992716, 0.036976717, -0.07429831, -0.0511...
3       [0.05929825, 0.10075583, -0.04815824, 0.041942...
4       [0.07565966, 0.017556518, -0.05588654, 0.03299...
                              ...
9995    [0.0059625385, 0.0012267067, 0.012396579, -0.0...
9996    [-0.0067766234, -0.0014006067, 0.008502565, 0....
9997    [0.017524539, 0.03087422, -0.06456015, -0.0359...
9998    [0.07474967, 0.022872753, -0.07786103, 0.03425...
9999    [0.016288364, 0.015901592, -0.04389199, 0.0022...
Name: vector, Length: 10000, dtype: object

## Беру только необходимые данные

In [41]:
test = a.copy()
data = test.loc[test['category'] == 1.0]
data

,id,description,vector,category
0,1159419,Лежит женщина,"[0.05818263, 0.032113455, -0.02853107, -0.0636...",1.0
6,1746970,Заявитель сотрудник полиции. Подозрение на хр...,"[0.042571373, 0.025118971, 0.006148531, -0.035...",1.0
14,1402615,Просит направить сотрудников полиции. Причину ...,"[0.014303841, 0.08098269, -0.07157798, 0.05430...",1.0
21,411003,В парке дебоширят 3 мужчин. Просит вызвать пол...,"[0.012720591, -0.027117958, -0.08578615, -0.00...",1.0
39,230042,звонила #ИМЯ# #ИМЯ#,"[-0.024676044, 0.08246049, -0.022930445, 0.074...",1.0
...,...,...,...,...
657,1699523,"Назревает драка, пятеро мужчин агрессивно себя...","[-0.030502232, 0.024443712, -0.043787878, -0.0...",1.0
663,1003390,"Запах газа в тамбуре, давления в газовой плите...","[0.014821596, -0.046150327, 0.0105473315, 0.05...",1.0
664,813227,"Слышно крики, постоянно шумят, возможно драка","[0.034836303, -0.019720629, -0.05340125, 0.065...",1.0
690,1139182,Подозрительный предмет. Рюкзак 30*40 серого цв...,"[0.021630738, -0.040502902, -0.119113155, 0.01...",1.0
696,676236,Запах гари в подъезде в 04 по тел (#ИМЯ#),"[0.06920649, 0.06162283, -0.07134408, 0.082978...",1.0

In [42]:
import nltk 

from nltk.tokenize import word_tokenize 

from nltk.util import ngrams, skipgrams 

nltk.download('punkt') 

#Функция нахождения N_gram 

def get_ngrams(text, n): 

    text = text.lower().replace(',', '').replace('.', '').replace('(', '').replace(')', '') 

    words = word_tokenize(text, language="russian") 

    n_grams = ngrams(words, n) 

    return [ ' '.join(grams) for grams in n_grams] 

#Функция нахождения Skip-gram 

def get_skipgrams(text, n,k): 

    text = text.lower().replace(',', '').replace('.', '').replace('(', '').replace(')', '') 

    words = word_tokenize(text, language="russian") 

    skip_grams = skipgrams(words, n,k) 

    return [ ' '.join(grams) for grams in skip_grams] 

#Вывести список биграмм

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\iamiw\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

## Делаем из правильных данных n-gram и skip-gram

In [43]:
# n-gram
n=2
n_gramms=[] 
for card in test['description']:
    n_gramms+=get_ngrams(card, n)

In [44]:
nfdist = nltk.FreqDist(n_gramms)
print(nfdist)

<FreqDist with 35793 samples and 78223 outcomes>

In [45]:
# s-gram
n=3
k=2
s_gramms=[] 
for card in test['description']:
    s_gramms+=get_skipgrams(card, n, k)

In [46]:
sfdist = nltk.FreqDist(s_gramms)
print(sfdist)

<FreqDist with 273000 samples and 349683 outcomes>

## Форматируем все данные и обращаем в список

In [47]:
a1 = []
df = []

In [48]:
for index, row in a.iterrows():
    a1.append(row['description'])

In [49]:
n = 10
for i in range (n):
    print(a1[i])
    i = i+1

Лежит женщина
#НОМЕР#. Дебоширит сын, принимает наркотические вещества
Драка 2 человека, в состоянии алкогольного опьянения. Мед. помощь не требуется
В дом Заявителя ломится знакомый. У Заявителя в руках ножи. Заявитель угрожает применить холодное оружие, если мужчина зайдет в дом.
Справка 103 (консультация)
Повтор. Упал сам, открытый перелом
 Заявитель сотрудник полиции. Подозрение на хранение наркотических веществ в ТС Тойота г.н. #ГОС.НОМЕР#.
Справка 112
Провал грунта,на месте где находился  канализационный люк.Глубина 2 метра,ширина 1,5 - метра
Бывший муж дебоширит, кричит. В квартире дети (6 и 8)лет

# Для точности проверки, необходимо убрать запятые

In [50]:
for i in range(len(a1)):
        a1[i] = str.lower(a1[i]).replace(',', '').replace('.', '').replace('(', '').replace(')', '')

In [51]:
for i in range (n):
    print(a1[i])
    i = i+1

лежит женщина
#номер# дебоширит сын принимает наркотические вещества
драка 2 человека в состоянии алкогольного опьянения мед помощь не требуется
в дом заявителя ломится знакомый у заявителя в руках ножи заявитель угрожает применить холодное оружие если мужчина зайдет в дом
справка 103 консультация
повтор упал сам открытый перелом
 заявитель сотрудник полиции подозрение на хранение наркотических веществ в тс тойота гн #госномер#
справка 112
провал грунтана месте где находился  канализационный люкглубина 2 метраширина 15 - метра
бывший муж дебоширит кричит в квартире дети 6 и 8лет

In [52]:
print(len(a1))

10000

## Сравниваем данные по спискам

In [53]:
enter = []
df = a.copy()

for i in range(len(a1)):
    s = a1[i]
    bigram =  n_gramms[i]
    skipgram = s_gramms[i]
    #Проверить вхождение биграммы (возвращает True/False) 
    s.find(bigram)>-1 
    #Проверить вхождение skip-граммы
    #Разбиваем skip-грамму на отдельные слова 
    words = skipgram.split() 
    #Объявляем переменную, содержащую признак вхождения skip-граммы в строку 
    if_in = True 
    #Перебираем список слов в skip-грамме и проверяем вхождение каждого из них в строку 
    if_in = if_in and (s.find(bigram)>-1)
    # если скипграмма нашлась ставим 1, если нет, то ставим ноль
    for w in words: 
        if if_in == True:
            df.at[i, 'category'] = 1
        else: 
            df.at[i, 'category'] = 0

In [54]:
df

,id,description,vector,category
0,1159419,Лежит женщина,"[0.05818263, 0.032113455, -0.02853107, -0.0636...",1.0
1,1201824,"#НОМЕР#. Дебоширит сын, принимает наркотически...","[0.007246209, 0.052625045, -0.004410434, -0.03...",0.0
2,1052343,"Драка 2 человека, в состоянии алкогольного опь...","[0.06992716, 0.036976717, -0.07429831, -0.0511...",0.0
3,987489,В дом Заявителя ломится знакомый. У Заявителя ...,"[0.05929825, 0.10075583, -0.04815824, 0.041942...",0.0
4,1376556,Справка 103 (консультация),"[0.07565966, 0.017556518, -0.05588654, 0.03299...",0.0
...,...,...,...,...
9995,641285,"Нет водоснабжения по нескольким улицам, трое с...","[0.0059625385, 0.0012267067, 0.012396579, -0.0...",0.0
9996,946051,Сильная боль в области живота.,"[-0.0067766234, -0.0014006067, 0.008502565, 0....",0.0
9997,769676,Знакомый мужчина справляет нужду на месте,"[0.017524539, 0.03087422, -0.06456015, -0.0359...",0.0
9998,1741072,Справка 103 консультация,"[0.07474967, 0.022872753, -0.07786103, 0.03425...",0.0
9999,1737742,"Справка 103, о госпитализации родственницы Зая...","[0.016288364, 0.015901592, -0.04389199, 0.0022...",0.0

## Оборачиваем все данные в таблицу

In [55]:
path = 'df2.xlsx' 
df.to_excel(path, index=False)